# netlify.toml
[build]
  # Assuming your frontend build command is 'npm run build'
  # and the output directory is 'dist'
  command = "npm run build"
  publish = "dist"
  # Tell Netlify where the functions are
  functions = "netlify/functions"

# Explicit mapping for base API route
[[redirects]]
  from = "/api"
  to   = "/.netlify/functions/api"
  status = 200
  force  = true

# Explicit mapping for API with trailing slash
[[redirects]]
  from = "/api/"
  to   = "/.netlify/functions/api"
  status = 200
  force  = true

# Wildcard mapping for all other API endpoints
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/api/:splat"
  status = 200
  force  = true

[dev]
  # Tell Netlify CLI that you are using Vite
  framework = "vite"
  # Tell Netlify CLI to connect to Vite on port 5175
  targetPort = 5175
  # Port for the Netlify Dev proxy server
  port = 9999
