# netlify.toml
[build]
  # Assuming your frontend build command is 'npm run build'
  # and the output directory is 'dist'
  command = "npm run build"
  publish = "dist"
  # Tell Netlify where the functions are
  functions = "netlify/functions"

[[redirects]]
  # Explicitly map the base API paths to the Netlify function
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  # Route requests from /api/* to the corresponding function
  from = "/api/*"
  to = "/.netlify/functions/api/:splat" # Rewrite to the function itself
  status = 200 # Rewrite status
  force = true

[dev]
  # Tell Netlify CLI that you are using Vite
  framework = "vite"
  # Tell Netlify CLI to connect to Vite on port 5175
  targetPort = 5175
  # Port for the Netlify Dev proxy server
  port = 9999
